{{- if .Values.enabled }}
apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  name: {{ .Values.function.name }}-trigger
  namespace: {{ .Values.namespace }}
spec:
  functionref:
    name: {{ .Values.function.name }}
    namespace: {{ .Values.namespace }}
    type: name
  relativeurl: {{ .Values.httptrigger.url }}
  method: {{ .Values.httptrigger.method }}
{{- end }}
