{{- if .Values.enabled }}
apiVersion: fission.io/v1
kind: Package
metadata:
  name: {{ .Values.function.name }}-pkg
  namespace: {{ .Values.namespace }}
spec:
  environment:
    name: {{ .Values.environment.name }}
    namespace: {{ .Values.namespace }}
  deployment:
    literal: {{ .Values.function.code | b64enc | quote }}
{{- end }}
