apiVersion: v1
kind: Secret
metadata:
  name: zitadel-secrets
type: Opaque
stringData:
  config.yaml: |
    Database:
      postgres:
        Host: 192.168.2.119
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          Password: "ChangeMe456!Zitadel"
          SSL:
            Mode: disable
    FirstInstance:
      Org:
        Human:
          Username: "admin@zitadel.local"
          Password: "ChangeMeAdmin123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: zitadel-masterkey
type: Opaque
stringData:
  masterkey: "x123456789012345678901234567891y"
