enabled: true
namespace: fission
environment:
  name: nodejs
  image: ghcr.io/fission/node-env
  version: v1
function:
  name: hello
  code: |
    module.exports = async function(context) {
        return {
            status: 200,
            body: "Hello, World from Fission!\n"
        };
    }
httptrigger:
  url: /hello
  method: GET
