{{- if .Values.prefect.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: {{ .Values.argocdNamespace | default "default" }}
  name: prefect
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prefecthq.github.io/prefect-helm
    chart: prefect-server
    targetRevision: {{ .Values.prefect.version }}
    helm:
      values: |
        {{- if .Values.prefect.image }}
        global:
          prefect:
            image:
              repository: {{ .Values.prefect.image.repository }}
              prefectTag: {{ .Values.prefect.image.tag }}
              {{- if .Values.prefect.image.pullSecrets }}
              pullSecrets:
                {{- range .Values.prefect.image.pullSecrets }}
                - {{ . }}
                {{- end }}
              {{- end }}
        {{- end }}
        postgresql:
          enabled: {{ .Values.prefect.postgresql.useEmbedded | default false }}
        {{- if not .Values.prefect.postgresql.useEmbedded }}
        secret:
          create: false
          name: {{ .Values.prefect.postgresql.existingSecret }}
        {{- end }}
        server:
          basicAuth:
            enabled: {{ .Values.prefect.basicAuth.enabled }}
            existingSecret: {{ .Values.prefect.basicAuth.existingSecret }}
          uiConfig:
            prefectUiApiUrl: {{ .Values.prefect.uiApiUrl | quote }}
          replicaCount: 1
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
        backgroundServices:
          runAsSeparateDeployment: false
        ingress:
          enabled: true
          tls: {{ .Values.prefect.ingress.tls }}
          selfSigned: {{ .Values.prefect.ingress.selfSigned }}
          host:
            hostname: {{ .Values.prefect.ingress.host }}
            path: /
            pathType: ImplementationSpecific
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.prefect.namespace | default "default" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
