{{- if .Values.windmill.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windmill
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://windmill-labs.github.io/windmill-helm-charts/
    chart: windmill
    targetRevision: {{.Values.windmill.version}}
    {{- if .Values.windmill.useConfigMapValues }}
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/{{.Values.windmill.configMapRepo}}/main/{{.Values.windmill.configMapPath}}
    {{- else if .Values.windmill.externalValuesFile }}
    helm:
      valueFiles:
        - {{.Values.windmill.externalValuesFile}}
    {{- else }}
    helm:
      values: |
        windmill:
          baseProtocol: https
          baseDomain: {{.Values.windmill.host}}
          {{- if .Values.windmill.databaseSecret.enabled }}
          databaseUrlSecretName: {{.Values.windmill.databaseSecret.name}}
          databaseUrlSecretKey: {{.Values.windmill.databaseSecret.key}}
          {{- end }}
        ingress:
          enabled: true
        postgresql:
          enabled: {{.Values.windmill.postgresql.enabled}}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}